name: Tests on all platforms

# TODO: change from push to pull request
on: [push]

jobs:
  testing:
    # needs: linting
    runs-on: ${{ matrix.os}}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: [windows-latest, ubuntu-latest]

      max-parallel: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv pip install -e .[dev]
        python -m uv pip install coverage pytest-cov

    - name: Runs test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: pytest --cov=. tests/ --cov-report=term-missing --cov-report markdown-append:$GITHUB_STEP_SUMMARY --durations=50 --verbose

    - name: Runs test (Windows)
      if: matrix.os == 'windows-latest'
      run: pytest --cov=. tests/ --cov-report=term-missing --cov-report markdown-append:$env:GITHUB_STEP_SUMMARY --durations=50 --verbose
